spring:
  application:
    name: greething-service



management:
  endpoints:
    web:
      exposure:
        include:
          - "*"



greething-service:
  greeting:"ola2"
  default-value:"Mundo"
